server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti_modeling?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000ms

activiti:
  process-definitions:
    cache:
      key: bpm#process#definition

