version: "3"
networks:
  ncm-net:
    external: true

services:
  ncm-mysql:
    image: mysql:8.0
    container_name: ncm-mysql
    restart: always
    networks:
      - ncm-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=goldenit
    volumes:
      - /data/golduser/soft/mysql/log:/var/log/mysql
      - /data/golduser/soft/mysql/data:/var/lib/mysql
      - /data/golduser/soft/mysql/conf:/etc/mysql/conf.d

  ncm-redis:
    image: redis:6.2.5
    container_name: ncm-redis
    restart: always
    networks:
      - ncm-net
    ports:
      - "6379:6379"
    command: ["redis-server","/etc/redis/redis.conf"]
    volumes:
      - /data/golduser/soft/redis/data:/data
      - /data/golduser/soft/redis/conf/redis.conf:/etc/redis/redis.conf
  

  ncm-minio:
    image: bitnami/minio:latest
    container_name: ncm-minio
    restart: always
    networks:
      - ncm-net
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - /data/golduser/soft/minio/data:/bitnami/minio/data

  zookeeper:
    image: zookeeper:3.4.14
    container_name: ncm-zookeeper
    restart: always
    networks:
      - ncm-net
    ports:
      - "2181:2181"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.88.148:9092
    volumes:
      - /data/golduser/soft/zookeeper/data:/data

  kafka:
    image: bitnami/kafka:2.8.1
    container_name: ncm-kafka
    restart: always
    networks:
      - ncm-net
    ports:
      - "9092:9092"
    #      - "9094:9094" ## 外网
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=ncm-zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.88.148:9092
    #      - KAFKA_ENABLE_KRAFT=yes
    #      - KAFKA_KRAFT_CLUSTER_ID=1
    #      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    #      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://ncm-kafka:9092,EXTERNAL://192.168.88.233:9094
    volumes:
      ## sudo chown -R 1001:1001 /data/kafka/data
      - /data/golduser/soft/kafka/data:/bitnami/kafka
    depend_on: ncm-zookeeper

  jobmanager:
    image: flink:1.15.0
    container_name: ncm-jobmanager
    restart: always
    networks:
      - ncm-net
    ports:
      - "18081:8081"
    command: jobmanager
#    command: standalone-job --job-classname com.job.ClassName [--job-id <job id>] [--fromSavepoint /path/to/savepoint [--allowNonRestoredState]] [job arguments]
#    command: standalone-job --job-classname com.goldenit.fmks.DemoEnvKafka
    volumes:
      - /data/golduser/soft/fmks:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ncm-jobmanager
#        parallelism.default: 2

  taskmanager:
    image: flink:1.15.0
    container_name: ncm-taskmanager
    restart: always
    networks:
      - ncm-net
    depends_on:
      - jobmanager
    command: taskmanager
    #    scale: 1
    volumes:
      - /data/golduser/soft/fmks:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ncm-jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2