version: "3"
services:
  #Service for backend
  server:
    image: hub.goldenit.com.cn/yj/ncm-server
    container_name: ncm-server
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=jx
    volumes:
      - ./server/logs:/app/logs

  data:
    image: hub.goldenit.com.cn/yj/ncm-data
    container_name: ncm-data
    restart: always
    ports:
      - 8090:8080
    environment:
      - SPRING_PROFILES_ACTIVE=jx
    volumes:
      - ./data/logs:/app/logs