server:
  port: 8100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable_ui?useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

flowable:
  history-level: AUDIT
  database-schema-update: false
  async-executor-activate: true