
package rules
import com.bpm.example.businessruletask.demo.model.CostCalculation;

//折扣规则1：消费金额不足5000元时，不打折
rule "rule1"
    no-loop true
    lock-on-active true
    when
       $s:CostCalculation(originalTotalPrice<5000)
    then
       $s.setDiscountRatio(1.0);
       $s.setActualTotalPrice($s.getOriginalTotalPrice() * 1.0);
       update($s)
       System.out.println("触发规则rule1：消费金额不足5000元时，不打折");
end
//折扣规则2：消费金额满5000元且不足10000元时，打九折
rule "rule2"
    no-loop true
    lock-on-active true
    when
       $s:CostCalculation(originalTotalPrice>=5000 && originalTotalPrice<10000)
    then
       $s.setDiscountRatio(0.9);
       $s.setActualTotalPrice($s.getOriginalTotalPrice() * 0.9);
       update($s)
       System.out.println("触发规则rule2：消费金额满5000元且不足10000元时，打九折");
end
//折扣规则3：消费额满10000元时，打八折
rule "rule3"
    no-loop true
    lock-on-active true
    when
       $s:CostCalculation(originalTotalPrice>=10000)
    then
       $s.setDiscountRatio(0.8);
       $s.setActualTotalPrice($s.getOriginalTotalPrice() * 0.8);
       update($s)
       System.out.println("触发规则rule3：消费金额满10000元时，打八折");
end

