bpm:
  engine-name: engine02
server:
  port: 8102
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti_engine02?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456