server:
  port: 8808

spring:
  cloud:
    nacos:
      discovery:
        service: bpm-gateway
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

pika:
  host: 127.0.0.1
  port: 9221
  timeout: 1000ms
  lettuce:
    pool:
      max-active: 50
      min-idle: 5
      max-idle: 10
      max-wait: 1000ms