server:
  port: 8808

spring:
  cloud:
    gateway:
      routes:
        - id: engine01-router
          uri: http://localhost:8101
          predicates:
            - Path=/processInstance/startByProcessDefinitionId/**
            - Weight=engine-group,5
        - id: engine02-router
          uri:  http://localhost:8102
          predicates:
            - Path=/processInstance/startByProcessDefinitionId/**
            - Weight=engine-group,5


engine-config:
    engines:
      - name: engine01
        url: http://localhost:8101
      - name: engine02
        url: http://localhost:8102
    pattens:
      - /task/complete/(.+)
      - /task/processInstance/(.+)

pika:
  host: 127.0.0.1
  port: 9221
  timeout: 1000ms
  lettuce:
    pool:
      max-active: 50
      min-idle: 5
      max-idle: 10
      max-wait: 1000ms