server:
  port: 9999

spring:
  data:
    mongodb:
      host:  127.0.0.1
      port: 27017
      username: admin
      password: '123456'
      database: flowable_history
      authentication-database: admin
  datasource:
    url: jdbc:mysql://localhost:3306/flowable_core?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 100ms

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer_group